---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mdxjvvvtl/goldenislandtours.com/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp east-coast.html $DEPLOYPATH
    - /bin/cp honeymoon-1.html $DEPLOYPATH
    - /bin/cp honeymoon-2.html $DEPLOYPATH
    - /bin/cp honeymoon-packages.html $DEPLOYPATH
    - /bin/cp inquire.html $DEPLOYPATH
    - /bin/cp north-coast.html $DEPLOYPATH
    - /bin/cp other-packages.html $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH
    - /bin/cp terms-conditions.html $DEPLOYPATH
    - /bin/cp tours.html $DEPLOYPATH
    - /bin/cp transport.html $DEPLOYPATH
    - /bin/cp trip-details.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
